#!/bin/bash -l

#SBATCH -A g2018003

#SBATCH -p core

#SBATCH -n 4

#SBATCH -t 4:00:00

#SBATCH -J TopHat_mapping_job

#SBATCH --mail-type=ALL

#SBATCH --mail-user caitlinvigetun@hotmail.com

out=$1

left=$2

right=$3

# Load modules

module load bioinfo-tools

module load bowtie/1.2.0

module load bowtie/2.3.2

module load tophat/2.1.1

# Your commands

tophat -o $out -p 4 sel3_NW_015504249.fna $left $right   
